### ISSUE TITLE
Can't build today. Some issues with submodules.

### ISSUE THREAD

**Issue by dalao3** [archfan/coreboot#12]
I'm following this guide (https://blog.conor-burns.com/lenovo-t440p-coreboot/) but I get some errors below. It appears there are issues with submodules. 
```
Skipping submodule '3rdparty/amd_blobs'
Skipping submodule '3rdparty/blobs'
Skipping submodule '3rdparty/fsp'
Skipping submodule '3rdparty/amd_blobs'
Skipping submodule '3rdparty/blobs'
Skipping submodule '3rdparty/fsp'
    HOSTCC     util/sconfig/main.o
    HOSTCC     util/sconfig/sconfig (link)
    SCONFIG    mainboard/lenovo/t440p/devicetree.cb
    OPTION     option_table.h
    CC         bootblock/mainboard/lenovo/t440p/static.o
cc1: error: 3rdparty/vboot/firmware/include: Not a directory
cc1: error: 3rdparty/vboot/firmware/2lib/include: Not a directory
cc1: error: 3rdparty/vboot/firmware/lib21/include: Not a directory
cc1: error: unrecognized command line option '-Wno-address-of-packed-member' [-Werror]
cc1: all warnings being treated as errors
make: *** [Makefile:365: build/bootblock/mainboard/lenovo/t440p/static.o] Error 1
```

If I copy the 3rdparty folder from coreboot's latest repo, I get the follow error. How to get a snapshot of the submodules when it was working?

```
Failed to clone 'util/nvidia/cbootimage' a second time, aborting
    CC         bootblock/lib/bootmode.o
In file included from src/security/vboot/misc.h:21,
                 from src/lib/bootmode.c:18:
src/security/vboot/vboot_common.h:21:10: fatal error: vboot_struct.h: No such file or directory
 #include <vboot_struct.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:365: build/bootblock/lib/bootmode.o] Error 1
```

**Comment by KratosPS** [comment]
I get the same error when I attempt to run make. Instead of replacing the entire 3rdparty folder i just replaced the vboot folder. Everything appears to run correctly up until vboot_struct.h can't be found. Tried running the 4.11_branch but don't have permissions to download the submodules. Tried to edit the .gitmodules file pointing to the same directories as t440p-main with vboot added and it appears to not download anything into vboot still.

**Comment by elkaps** [comment]
I managed to run make by using vboot from the following branch:
https://github.com/coreboot/coreboot/tree/4.11_branch
For some reason I got the error 
`make: *** No rule to make target '".car.data"', needed by 'build/coreboot.pre'.  Stop.
`
which was resolved after copying the Makefile.inc as well.

**Comment by KratosPS** [comment]
> I managed to run make by using vboot from the following branch:
> https://github.com/coreboot/coreboot/tree/4.11_branch
> For some reason I got the error
> `make: *** No rule to make target '".car.data"', needed by 'build/coreboot.pre'. Stop. `
> which was resolved after copying the Makefile.inc as well.

This worked for me also. Thanks for the help elkaps, I was using the official build of coreboot which is still missing fixes for the touchpad buttons and other minor things.

**Comment by sudo-gedit** [comment]
Can you please provide me with your configuration. unfortunately I can't do it. Thank you

**Comment by acaleechurn** [comment]
Did someone manage to find out why the build is failing? I wanted to use this repo as it had the latest patches [which may not be true anymore] but ended up using the latest official release. Unfortunately my test clip broke and I could not test the generated ROM but as I'm getting new ones on Friday I wanted to give it a try again.

**Comment by acaleechurn** [comment]
If anyone is looking at Corebooting their T440p, the official repo now has the necessary patches to make everything work except for audio. Mine works well with tianocore compiled from the mainstream repo.

**Comment by hgandhi0626** [comment]
Did anyone manage to resolve this issue:
make: *** No rule to make target '".car.data"', needed by 'build/coreboot.pre'.  Stop.

I am using tag 4.9 from coreboot to build a firmware image for my PC engines ALIX2d board. I am stuck at this issue. Any help would be appreciated.
